### ISSUE TITLE
The user does not have sufficient permissions for this file

### ISSUE THREAD

**Issue by 547555909** [arghyac35/aria-telegram-mirror-bot#110]
when i do the step 13 “In the terminal, it'll ask you to visit an authentication URL. Visit it, grant access, copy the code on that page, and paste it in the terminal.”
the logs shows “Token stored to ./credentials.json
d300dea12bdb4aeb: Failed to upload - /mnt/pan/downloads/61dd1498-c0c7-4fb7-adc6-5477925a8756/old_heroku_guide.md: The user does not have sufficient permissions for this file.                                     
cleanup: Deleted 61dd1498-c0c7-4fb7-adc6-5477925a8756”
I guarantee my paste code is correct

**Comment by arghyac35** [comment]
> when i do the step 13 “In the terminal, it'll ask you to visit an authentication URL. Visit it, grant access, copy the code on that page, and paste it in the terminal.”
> the logs shows “Token stored to ./credentials.json
> d300dea12bdb4aeb: Failed to upload - /mnt/pan/downloads/61dd1498-c0c7-4fb7-adc6-5477925a8756/old_heroku_guide.md: The user does not have sufficient permissions for this file.
> cleanup: Deleted 61dd1498-c0c7-4fb7-adc6-5477925a8756”
> I guarantee my paste code is correct

Check the account have proper access to the folder. This is issue with the account or drive.

**Comment by 547555909** [comment]
> Check the account have proper access to the folder. This is issue with the account or drive.

Is GDRIVE_PARENT_DIR_ID not support GOOGLE Shared Drives?

**Comment by 547555909** [comment]
I

> > when i do the step 13 “In the terminal, it'll ask you to visit an authentication URL. Visit it, grant access, copy the code on that page, and paste it in the terminal.”
> > the logs shows “Token stored to ./credentials.json
> > d300dea12bdb4aeb: Failed to upload - /mnt/pan/downloads/61dd1498-c0c7-4fb7-adc6-5477925a8756/old_heroku_guide.md: The user does not have sufficient permissions for this file.
> > cleanup: Deleted 61dd1498-c0c7-4fb7-adc6-5477925a8756”
> > I guarantee my paste code is correct
> 
> Check the account have proper access to the folder. This is issue with the account or drive.

I'm sure my account has full permissions to the folder
