### ISSUE TITLE
Something wrong with DOCKER Deploy

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [arghyac35/aria-telegram-mirror-bot#157]
Something is uncompatible with docker deployment, can you check and add CMDs to deploy using docker on AWS Server.
I've to use sudo screen to run this for now.

**Comment by arghyac35** [comment]
If using aws EC2 with linux environment, then why to use docker? You can deoloy it as normal NodeJs app and either use PM2 or systemd to keep it running.

**Comment by ParveenBhadooOfficial** [comment]
> If using aws EC2 with linux environment, then why to use docker? You can deploy it as normal NodeJs app and either use PM2 or systemd to keep it running.

Thank You, will try that.
