### ISSUE TITLE
Heroku logs are fines but bot is not working

### ISSUE THREAD

**Issue by dhairya137** [arghyac35/aria-telegram-mirror-bot#214]
![Screenshot from 2021-07-11 14-29-07](https://user-images.githubusercontent.com/40421470/125189181-6a17b180-e254-11eb-8fe2-cf70ad9a16d2.png)

In my heroku logs showing bot is ready but my bot is not running.

**Comment by arghyac35** [comment]
If trying in group then check bot is added as admin.
