### ISSUE TITLE
erorr while Starting the bot

### ISSUE THREAD

**Issue by Godofh3ell** [arghyac35/aria-telegram-mirror-bot#55]
![Screenshot_2020-12-03-16-15-34-311_com termux](https://user-images.githubusercontent.com/66544811/101001625-5a7d0f80-3585-11eb-908b-e9c040a7e9a5.jpg)
tell me how to fix this error!

**Comment by arghyac35** [comment]
accounts/ folder is required in project root when you use service account.

if not using service account but still facing the issue then check if you have the latest commit, cause it is fixed in https://github.com/arghyac35/aria-telegram-mirror-bot/commit/52739e37e876f457c8525478eafaca8d4db01802

**Comment by Godofh3ell** [comment]
Added acounts and also but set  service a/c to false and also useing the lated commit but still same error.. Help me how to solve it

**Comment by Godofh3ell** [comment]
![Screenshot_2020-12-07-10-54-17-030_com termux](https://user-images.githubusercontent.com/66544811/101312837-c491ff00-387a-11eb-964d-09cca0f1e9ad.jpg)
 This is the error this time - added accounts and still this error
