### ISSUE TITLE
Service Accounts Don't switch while uploading 

### ISSUE THREAD

**Issue by noonegupta734** [arghyac35/aria-telegram-mirror-bot#83]
Sas don't switch while uploading resulting in rate limit error

**Comment by arghyac35** [comment]
Can you please confirm if this issue is fixed, cause I pushed a fix dew days ago https://github.com/arghyac35/aria-telegram-mirror-bot/commit/7c227a977a6c43e1e83ddea33aef5d1c1c22183d

**Comment by noonegupta734** [comment]
Yeah I'll deploy and check 😅😅😅
I'll close this issue sorry
