### ISSUE TITLE
rarbg and 1337x torrents wont start

### ISSUE THREAD

**Issue by askfriends** [arghyac35/aria-telegram-mirror-bot#96]
as said torrents from rarbg and 1337x are not getting started, stuck at 0%

some example magent urls
https://1337x.is/torrent/4775169/Monster-Hunter-2021-720p-WEBRip-800MB-x264-GalaxyRG/
https://rarbgget.org/torrent/iznhwyk

![12](https://user-images.githubusercontent.com/2517219/108050932-179ee400-706c-11eb-9875-01849035afdb.png)

**Comment by arghyac35** [comment]
Most of the torrents I tried from 1337x do start, it is related to the torrent tracker itself. So, it might be an issue with the torrent not with the bot.

**Comment by 547555909** [comment]
> Most of the torrents I tried from 1337x do start, it is related to the torrent tracker itself. So, it might be an issue with the torrent not with the bot.

The reason for this problem is that the download folder is not automatically created and needs to be created manually to solve it

**Comment by askfriends** [comment]
> > Most of the torrents I tried from 1337x do start, it is related to the torrent tracker itself. So, it might be an issue with the torrent not with the bot.
> 
> The reason for this problem is that the download folder is not automatically created and needs to be created manually to solve it

and how to do that?

**Comment by 547555909** [comment]
> > > Most of the torrents I tried from 1337x do start, it is related to the torrent tracker itself. So, it might be an issue with the torrent not with the bot.
> > 
> > 
> > The reason for this problem is that the download folder is not automatically created and needs to be created manually to solve it
> 
> and how to do that?

create the download folder manually

**Comment by arghyac35** [comment]
> > Most of the torrents I tried from 1337x do start, it is related to the torrent tracker itself. So, it might be an issue with the torrent not with the bot.
> 
> The reason for this problem is that the download folder is not automatically created and needs to be created manually to solve it

No, u r wrong, download folder gets created automatically if it doesn't exist.

**Comment by 547555909** [comment]
> > > Most of the torrents I tried from 1337x do start, it is related to the torrent tracker itself. So, it might be an issue with the torrent not with the bot.
> > 
> > 
> > The reason for this problem is that the download folder is not automatically created and needs to be created manually to solve it
> 
> No, u r wrong, download folder gets created automatically if it doesn't exist.

But in fact, the download folder is not automatically created

**Comment by arghyac35** [comment]
If it doesn't for you, then check that aria2c have permissions to create
folders.
